### ISSUE TITLE
Wrong Jitsi Link is sent to non-Quadrix users

### ISSUE THREAD

**Issue by alpabrz** [alariej/quadrix#15]
Hey, I'm currently testing out this app since I'd like to add it to [this app list](https://linuxphoneapps.org). While trying out video conferencing, I stumbled upon a strange bug:
+ Between Quadrix users, video conferencing works just fine.
+ However, if trying to call an Element (or Hydrogen) user, a wrong URL will be sent to him/her: e.g. `https://jitsi.riot.im?chat.quadrix.kusvpktjsumrrzy` instead of `https://jitsi.riot.im/chat.quadrix.kusvpktjsumrrzy`

Unfortunately, I know nothing about TypeScript or ReactXP and don't know how to debug this. But I figured I'd report it anyway for completion's sake.

**Quadrix Version:** 1.2.1 (via Flathub)
**Operating System:** Arch Linux ARM (w/ Phosh)
**Element Version:** Nightly 2022071901; **Hydrogen Version:** v0.2.33

Other than that, Quadrix works quite well on those Linux Mobile systems (except of some input issues seemingly related to Electron), thanks for creating such a nice straightforward Matrix Client :+1:

**Comment by alariej** [comment]
Thanks for the bug report. I will check it and come back today or tomorrow..

**Comment by alpabrz** [comment]
Thank you! If there's something I can do to help like collecting logs or so I'd be glad to do it.

**Comment by alariej** [comment]
Good catch, the "?" was either my mistake, or something has changed on the Jitsi side. In any case this commit https://github.com/alariej/quadrix/commit/6c204ff45f7aff05e76b432c51b23e8334161f51 replaces the "?" with "/". I just tested it on Hydrogen and it seems to works. I will push Quadrix version 1.2.2 in the next hours so it should be soon available on Linux as Snap and Flatpak. Other platforms will follow a bit later.

By the way, it would be great to have Quadrix on LinuxPhoneApps. Thanks!

**Comment by alpabrz** [comment]
Wow, you're really fast! That wouldn't have been necessary. Regarding LinuxPhoneApps, I've already [opened a Merge Request there](https://framagit.org/linmobapps/linmobapps.frama.io/-/merge_requests/34), if you're interested in taking a look - hope I didn't get anything wrong there!

**Comment by alariej** [comment]
Merge Request looks good! I've just joined #linuxphoneapps:matrix.org, do post an update if / when Quadrix is listed. Thanks again!
