### ISSUE TITLE
[unknown error] when trying to log in

### ISSUE THREAD

**Issue by habi** [alariej/quadrix#16]
I'd like to use Version 1.2.0 on an iPhone 12 mini with iOS 15.6, but when I want to log in, I get a modal `[unknown error]` message.
I clicked the three dots on the right to use the '@user:server.tld' field/notation.
And I'm using Bitwarden to copy-paste my password so I'm quite sure that there's no typo in the password...

**Comment by alariej** [comment]
Hi, thanks for opening the issue. I haven't seen this problem so far with my current test user group. Did you also try entering your user ID and server separately in the respective entry fields (which is the default login mask)? Are you on a private homeserver, or on a public one like matrix.org? Can you try login into the same account using https://app.quadrix.chat, just to see if you get the same error? Thanks.

**Comment by alariej** [comment]
Just checked my code. It's not a wrong password, otherwise you would get an "Invalid password" error. And the server doesn't seem to return any error details, that's why the code generates "[unknown error]". Do you know the type of server (Synapse, Dendrite, Conduit) your are trying to access?

**Comment by habi** [comment]
> Did you also try entering your user ID and server separately in the respective entry fields (which is the default login mask)?

Sure, but does not work.

> Are you on a private homeserver, or on a public one like matrix.org?

![image](https://user-images.githubusercontent.com/1651235/184690129-47e61aeb-1517-44d3-b251-2919f7e23f5d.jpeg)
Public, matrix.org

> Can you try login into the same account using https://app.quadrix.chat, just to see if you get the same error?

Logging in on the website works fine.

**Comment by habi** [comment]
I'm using the firewall feature of https://1blocker.com to block ads/trackers on my phone.
But this should also block things/login directly on the website, no?

**Comment by alariej** [comment]
OK thanks for the info. I installed the 1blocker app on my iPhone (also iOS 15.6) to try to reproduce the issue, but the Firewall option is premium. I guess the easiest would be for you to do a quick test by disabling 1blocker and trying to login on Quadrix again. At least it would confirm whether Quadrix has an issue with 1blocker (and perhaps other ad blockers) or not. I know around 10 users with iPhone versions from 7 to 11 and no-one has had login issues so far, on matrix.org or private homeservers.

**Comment by habi** [comment]
I disabled everything I could in 1Blocker, but the problem still persists...
![image](https://user-images.githubusercontent.com/1651235/184700606-b29385d7-0e69-4662-b891-ff54d6f71c8a.png)

**Comment by habi** [comment]
When I deliberately enter a wrong password I get the same 'unknown error' on iOS.
The website does tell me that the username or password is invalid...

It's there somehow a log I can access and provide?

**Comment by alariej** [comment]
OK interesting. Your last test hints at a completely failed connection from the app to the server. There is unfortunately no log you can access on the production version of the app. For debugging you'd have to clone the Quadrix repo, and run the React Native development server on a Mac to serve the app on your phone. Are you successfully using other Matrix clients on your phone, such as Element or FluffyChat?

**Comment by habi** [comment]
> Are you successfully using other Matrix clients on your phone, such as Element or FluffyChat?

Successfully using both, but I'm happy to try out new apps, hence I'm here.

**Comment by alariej** [comment]
Quadrix does detect that your phone is connected to the internet, otherwise you'd get a specific error message related to that. But for some reason the call to the REST API on the Matrix server seems to fail on your phone. I've re-installed the 1blocker app on my phone and played with various settings: No success at reproducing your issue. I've installed Quadrix on the iPhone 12 mini simulator on my Mac: Runs without problem. I'm running out of ideas :-(

**Comment by alariej** [comment]
I seem to have found a way to reproduce the "unkown error" on my iPhone: 1) Enter a wrong password and try to login -> "wrong password" error, 2) Re-enter any password (correct or wrong) and try to login again -> "unknown error". There seems to be a combination of things, including a weird race condition, triggered by entering a wrong password. I can only see this in iOS, and it could be related to your issue.

You could try to confirm this by killing the app (remove it from the apps in the phone's background), and try to login again. If you enter a correct password in the first attempt, does the login succeed?

**Comment by habi** [comment]
I completely turn off my phone during the night and started the app again today.
This is probably equivalent to killing the app :)
Logging in worked as expected now, so it must be related to your mentioned race condition, e.g. me having entered something wrong on the first try.

Thanks for the investigation and help!
Looking forward to test-drive the app some more soon.
