### ISSUE TITLE
Keep crashing when trying to read encrypted messages

### ISSUE THREAD

**Issue by rilysh** [alariej/quadrix#20]
When I click to view encrypted messages, quadrix keep crashing
![Screenshot_20220925-085258_Quadrix](https://user-images.githubusercontent.com/71683721/192127021-baf9c7e2-5e15-44a5-9865-17e0859491d1.jpg)

![Screenshot_20220925-085140_One UI Home](https://user-images.githubusercontent.com/71683721/192127028-3580e482-58f5-44bd-b7aa-1dfb86a56aeb.jpg)

**Comment by alariej** [comment]
Thanks for reporting. I'll look at this and push an update as soon as possible.

**Comment by alariej** [comment]
OK found the bug. Will publish v1.3.5 today + tomorrow...

**Comment by alariej** [comment]
I think this should be solved with https://github.com/alariej/quadrix/commit/cfbca03946bacb4fde4b43f6e99af2ae4f9437e7, so I'll close, but feel free to re-open if you still have the issue.
